# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Messaging'

  # Pods for ChatApp

  target 'ChatApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
